"""Compatibility exports for the public multi-pass interpretation harness.

The scientific implementation lives in :mod:`medical_image_harness.multipass`.
This module preserves the original private-package import path for the desktop
application while keeping the dependency direction private -> public.
"""

from medical_image_harness.multipass import (
    DEFAULT_MAX_EKG_SYSTEMATIC_PROBES,
    DEFAULT_MAX_LOCAL_CANDIDATE_AREA,
    DEFAULT_MAX_NORMAL_SAFETY_PROBES,
    DEFAULT_MIN_REFINE_CROP_EDGE_PX,
    DEFAULT_MIN_ZOOM_SOURCE_EDGE_PX,
    BboxCalibrator,
    ImageCropper,
    MultiPassAnalyzer,
    MultiPassInterpreter,
    RefinementAction,
    RefinementAnalyzer,
    RefinementDelta,
    RefinementResult,
    ReportFinalizer,
    apply_refinement_delta,
    build_manual_zoom_message,
    clamp_unit,
    covering_region,
    expand_crop_to_min_source_edge,
    needs_manual_zoom,
    pad_region,
    reconcile_final_report,
    region_source_edge_px,
    remap_bbox,
    select_ekg_systematic_probe_regions,
    select_local_candidate_targets,
    select_normal_safety_probe_regions,
    select_zoom_targets,
)

__all__ = [
    "DEFAULT_MAX_EKG_SYSTEMATIC_PROBES",
    "DEFAULT_MAX_LOCAL_CANDIDATE_AREA",
    "DEFAULT_MAX_NORMAL_SAFETY_PROBES",
    "DEFAULT_MIN_REFINE_CROP_EDGE_PX",
    "DEFAULT_MIN_ZOOM_SOURCE_EDGE_PX",
    "BboxCalibrator",
    "ImageCropper",
    "MultiPassAnalyzer",
    "MultiPassInterpreter",
    "RefinementAction",
    "RefinementAnalyzer",
    "RefinementDelta",
    "RefinementResult",
    "ReportFinalizer",
    "apply_refinement_delta",
    "build_manual_zoom_message",
    "clamp_unit",
    "covering_region",
    "expand_crop_to_min_source_edge",
    "needs_manual_zoom",
    "pad_region",
    "reconcile_final_report",
    "region_source_edge_px",
    "remap_bbox",
    "select_ekg_systematic_probe_regions",
    "select_local_candidate_targets",
    "select_normal_safety_probe_regions",
    "select_zoom_targets",
]
