"""Generated from clinical_knowledge YAML; do not edit by hand."""

from __future__ import annotations

REGISTRY_SHA256 = "d22a03e037293636c86ca029452a8486f93f5625cb5655b3381088b8cc1fc22c"

REGISTRY_DIGEST_SCOPE = "canonical-input-documents-v1"

BUILTIN_RULE_SPECS: tuple[dict[str, object], ...] = ({'canonical_rule_id': 'cxr.pneumothorax_undercall.v1',
  'id': 'cxr-pneumothorax-undercall',
  'modality': 'CXR',
  'description': '若輸出肯定提及 pneumothorax，整體結果不可仍為 normal/info。規則修正 模型自身的分流矛盾並要求 critical '
                 '人工複核；它不從關鍵字推斷大小、 張力生理或治療方式，這些必須由可見影像與臨床狀態分別判斷。',
  'conditions': [{'field': 'all_text',
                  'op': 'contains_any_asserted',
                  'values': ['pneumothorax', '氣胸']},
                 {'field': 'severity', 'op': 'severity_at_most', 'value': 'info'}],
  'message': '判讀提及氣胸卻評為非異常 — 需人工排除（張力性）氣胸',
  'guideline': 'BTS: Guideline for Pleural Disease',
  'guideline_version': '2023',
  'effective_date': '2023-07-01',
  'source_url': 'https://www.brit-thoracic.org.uk/clinical-resources/guidelines/pleural-disease/',
  'escalate_to': 'critical',
  'require_review': True},
 {'canonical_rule_id': 'cxr.widened_mediastinum.v1',
  'id': 'cxr-widened-mediastinum',
  'modality': 'CXR',
  'description': '若輸出肯定描述 widened mediastinum，整體結果不可仍為 normal/info；至少 升為 warning '
                 '並由專科醫師核對急性主動脈疾病及其他原因。此徵象非特異， 胸片也不能單獨確認或排除 acute aortic syndrome。',
  'conditions': [{'field': 'all_text',
                  'op': 'contains_any_asserted',
                  'values': ['widened mediastinum',
                             'mediastinal widening',
                             '縱膈腔變寬',
                             '縱隔變寬']},
                 {'field': 'severity', 'op': 'severity_at_most', 'value': 'info'}],
  'message': '縱膈腔變寬卻評為非異常 — 需人工排除主動脈病變',
  'guideline': 'ACR: Appropriateness Criteria — Suspected Acute Aortic Syndrome',
  'guideline_version': '2021',
  'effective_date': '2021-01-01',
  'source_url': 'https://acsearch.acr.org/docs/69402/Narrative',
  'escalate_to': 'warning',
  'require_review': True},
 {'canonical_rule_id': 'ekg.explicit_stemi_undercall.v1',
  'id': 'ekg-explicit-stemi-undercall',
  'modality': 'EKG',
  'description': '若輸出已肯定宣稱 STEMI、急性心肌梗塞或急性心肌損傷，整體結果不可仍 為 '
                 'normal/info。規則只修正模型自身的語意矛盾；心肌梗塞的臨床確診仍 需要心肌損傷證據與缺血脈絡，不能由截圖單獨完成。',
  'conditions': [{'field': 'all_text',
                  'op': 'contains_any_asserted',
                  'values': ['stemi',
                             'st elevation myocardial infarction',
                             'acute myocardial infarction',
                             'acute mi',
                             'acute myocardial injury',
                             'acute injury pattern',
                             '急性心肌梗塞',
                             '急性心肌損傷']},
                 {'field': 'severity', 'op': 'severity_at_most', 'value': 'info'}],
  'message': '判讀明確宣稱急性心肌梗塞/損傷卻評為非異常，需立即人工複核',
  'guideline': 'ESC/ACC/AHA/WHF: Fourth Universal Definition of Myocardial Infarction',
  'guideline_version': '2018',
  'effective_date': '2018-08-25',
  'source_url': 'https://academic.oup.com/eurheartj/article/40/3/237/5079081',
  'escalate_to': 'critical',
  'require_review': True},
 {'canonical_rule_id': 'ekg.peaked_t_hyperkalemia.v1',
  'id': 'ekg-peaked-t-hyperkalemia',
  'modality': 'EKG',
  'description': '輸出若肯定描述 peaked/tented T waves，整體結果不可仍為 normal/info； '
                 '應提示高血鉀與其他急性再極化異常的鑑別。ECG 所見的敏感度與特異度 都有限，規則不得把高尖 T 波單獨轉成確定高血鉀診斷。',
  'conditions': [{'field': 'checklist.t_wave',
                  'op': 'contains_any_asserted',
                  'values': ['peaked', 'tented', 'tall t', '高尖', '帳篷']},
                 {'field': 'severity', 'op': 'severity_at_most', 'value': 'info'}],
  'message': 'T 波高尖卻評為正常 — 需人工排除高血鉀',
  'guideline': 'AHA: Adult and Pediatric Special Circumstances of Resuscitation',
  'guideline_version': '2025',
  'effective_date': '2025-10-22',
  'source_url': 'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/adult-and-pediatric-special-circumstances-of-resuscitation',
  'escalate_to': 'warning',
  'require_review': True},
 {'canonical_rule_id': 'ekg.possible_hyperacute_ischemia_triage.v1',
  'id': 'ekg-possible-hyperacute-ischemia-triage',
  'modality': 'EKG',
  'description': '當輸出保留 hyperacute ischemia／hyperacute ischemic T-wave 的非否定 '
                 '鑑別，應保留不確定性但升級為 critical 專科複核。規則不把「possible」 '
                 '改寫成肯定診斷，而是避免時間敏感的鑑別被低嚴重度掩蓋。',
  'conditions': [{'field': 'all_text',
                  'op': 'contains_any_non_negated',
                  'values': ['hyperacute ischemia', 'hyperacute ischemic t wave']},
                 {'field': 'severity', 'op': 'severity_at_most', 'value': 'warning'}],
  'message': '判讀未排除超急性缺血性 T 波，維持不確定診斷但升級為急症人工複核',
  'guideline': 'ACC/AHA/ACEP/NAEMSP/SCAI: Guideline for the Management of Patients '
               'With Acute Coronary Syndromes',
  'guideline_version': '2025',
  'effective_date': '2025-02-27',
  'source_url': 'https://professional.heart.org/en/science-news/2025-guideline-for-the-management-of-patients-with-acute-coronary-syndromes',
  'escalate_to': 'critical',
  'require_review': True},
 {'canonical_rule_id': 'ekg.st_elevation_not_flagged.v1',
  'id': 'ekg-st-elevation-not-flagged',
  'modality': 'EKG',
  'description': '當可見 ST segment 軸已描述抬高且狀態不正常，整體結果仍標為 normal/info '
                 '時，至少需要專科醫師複核。這是輸出一致性安全網；ST 抬高本身不等同 STEMI，也不可只憑截圖宣告心肌梗塞。',
  'conditions': [{'field': 'checklist.st_segment',
                  'op': 'contains_any',
                  'values': ['elevat', 'ste ', 'st elevation', '抬高', '上升']},
                 {'field': 'checklist.st_segment.status',
                  'op': 'severity_at_least',
                  'value': 'info'},
                 {'field': 'severity', 'op': 'severity_at_most', 'value': 'info'}],
  'message': 'ST 段有抬高描述但整體嚴重度偏低，請人工確認是否為良性變異或急性缺血',
  'guideline': 'ESC/ACC/AHA/WHF: Fourth Universal Definition of Myocardial Infarction',
  'guideline_version': '2018',
  'effective_date': '2018-08-25',
  'source_url': 'https://academic.oup.com/eurheartj/article/40/3/237/5079081',
  'escalate_to': None,
  'require_review': True},
 {'canonical_rule_id': 'ekg.uncertain_acute_injury_with_st_elevation_triage.v1',
  'id': 'ekg-uncertain-acute-injury-with-st-elevation-triage',
  'modality': 'EKG',
  'description': '非正常 ST-elevation 軸若同時保留急性缺血、急性心肌損傷或急性冠狀動脈 阻塞的非否定鑑別，不可停留在 warning '
                 '以下。規則維持 diagnostic uncertainty，只把時間敏感的人工複核提升至 critical。',
  'conditions': [{'field': 'checklist.st_segment',
                  'op': 'contains_any',
                  'values': ['elevat', 'ste ', 'st elevation', '抬高', '上升']},
                 {'field': 'checklist.st_segment.status',
                  'op': 'severity_at_least',
                  'value': 'warning'},
                 {'field': 'all_text',
                  'op': 'contains_any_non_negated',
                  'values': ['acute anterior injury',
                             'acute myocardial injury',
                             'acute injury pattern',
                             'acute ischemia',
                             'acute coronary occlusion',
                             '急性心肌損傷',
                             '急性缺血']},
                 {'field': 'severity', 'op': 'severity_at_most', 'value': 'warning'}],
  'message': '異常 ST 段抬高且未排除急性缺血/心肌損傷，保留不確定診斷並升級為急症人工複核',
  'guideline': 'ACC/AHA/ACEP/NAEMSP/SCAI: Guideline for the Management of Patients '
               'With Acute Coronary Syndromes',
  'guideline_version': '2025',
  'effective_date': '2025-02-27',
  'source_url': 'https://professional.heart.org/en/science-news/2025-guideline-for-the-management-of-patients-with-acute-coronary-syndromes',
  'escalate_to': 'critical',
  'require_review': True})
